### ISSUE TITLE
Editing Election Bug

### ISSUE THREAD

**Issue by beckyetroy** [beckyetroy/SETUSU-Vote#59]
**Description**: When testing the current admin functionality, the following MySQL error occurred when trying to edit an election:

```
Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2022-11-10 15:11:00:00' for column 'OpenTime' at row 1
    at Query.Sequence._packetToError (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at PoolConnection.query (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\20088\Documents\FYP\SETUSU-Vote\routes\admin_interface.js:162:24
    at Ping.onOperationComplete (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\Pool.js:110:5)
    at Ping.<anonymous> (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\Connection.js:526:10)
    at Ping._callback (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\Connection.js:488:16)
    at Ping.Sequence.end (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Ping.Sequence.OkPacket (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\protocol\sequences\Sequence.js:92:8)      
    at Protocol._parsePacket (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\20088\Documents\FYP\SETUSU-Vote\node_modules\mysql\lib\protocol\Parser.js:433:10) {
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlMessage: "Incorrect datetime value: '2022-11-10 15:11:00:00' for column 'OpenTime' at row 1",
  sqlState: '22007',
  index: 0,
  sql: '\n' +
    '        UPDATE Election\n' +
    '        SET Description = "Test", \n' +
    '        ElectionDate = "2022-11-10", \n' +
    '        OpenTime = "2022-11-10 15:11:00:00", \n' +
    '        CloseTime = "2022-11-10 16:11:00:00" \n' +
    '        WHERE id = "4"\n' +
    '        '
}
```
Investigate and fix this bug.

**Story Points:** 3

**Comment by beckyetroy** [comment]
Fixed and awaiting PR.
